language: python
python:
  - "3.5"
  - "3.6"
fail_fast: true  
install:
  - pip install -r requirements.txt
# command to run tests
before_install:
  - pip install --upgrade pip
script:
  - find . -name \*.py -exec pycodestyle --ignore=E402 {} +
  - python tests/tests.py
