site_name: odufrn-downloader
site_url: https://github.com/odufrn/odufrn-downloader
site_description: Pacote para baixar os dados do portal de dados abertos da UFRN.
site_author: Open Data UFRN

nav:
    - Instalação: index.md
    - Guia de uso:
        - Guia geral: guia-geral.md
        - Guia Group: guia-group.md
        - Guia Package: guia-package.md
        - Guia Tag: guia-tag.md

repo_url: https://github.com/odufrn/odufrn-downloader

theme: readthedocs